site_name: DJITelloPy API Reference
site_url: "https://djitellopy.readthedocs.io/en/latest/"
repo_url: "https://github.com/damiafuentes/DJITelloPy"
repo_name: "damiafuentes/DJITelloPy"

theme:
  name: "material"

markdown_extensions:
  - admonition
  - codehilite

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - djitellopy/